name: Create new Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: [ 8.2, 8.3, 8.4 ]

    name: Test on PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer update

      - name: Run PHPunit
        run: composer run test:unit:coverage:clover

      - name: Upload coverage to Codecov
        if: ${{ matrix.php-versions }} == '8.4'
        uses: codecov/codecov-action@v5
        with:
          files: .phpunit.coverage/coverage-clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    name: Release
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5
        with:
          version-file: './composer.json'
          skip-on-empty: 'false'
          github-token: ${{ secrets.github_token }}
